spring:
  application:
    name: back-reservAR
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: validate
  jackson:
    time-zone: UTC
    serialization:
      write-dates-as-timestamps: false

jwt:
  secret: ${JWT_SECRET}

mercado-pago:
  access-token: ${MERCADO-PAGO_TOKEN}
  webhook-url: ${MERCADO-PAGO_WEBHOOK_URL}

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"