services:
  reservar-db:
    image: postgres:16
    container_name: reservar_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U reservar_user -d reservar_db" ]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - reservar-db:/var/lib/postgresql/data
    networks:
      - reservar
    ports:
      - "5433:5432"
  reservar-app:
    build:
      context: ./back-reservAr
      dockerfile: Dockerfile
    container_name: reservar_app
    restart: on-failure
    depends_on:
      reservar-db:
        condition: service_healthy
    environment:
      JWT_SECRET: ${JWT_SECRET}
      MERCADO-PAGO_TOKEN: ${MERCADO-PAGO_TOKEN}
      MERCADO-PAGO_WEBHOOK_URL: ${MERCADO-PAGO_WEBHOOK_URL}
      SPRING_DATASOURCE_URL: ${RESERVAR_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${RESERVAR_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${RESERVAR_DATASOURCE_PASSWORD}
    networks:
      - reservar
    ports:
      - "8080:8080"

volumes:
  reservar-db:

networks:
  reservar: