CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email    VARCHAR(50) NOT NULL UNIQUE ,
    password VARCHAR(255) NOT NULL,
    name     VARCHAR(50) NOT NULL,
    surname  VARCHAR(50) NOT NULL,
    phone    VARCHAR(20) NOT NULL,
    role     VARCHAR(20) NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CHECK (role IN ('ADMIN','CUSTOMER','STAFF'))
);

CREATE INDEX IF NOT EXISTS idx_role
    ON users (role, email DESC);