CREATE TABLE restaurants
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(120)                            NOT NULL,
    address VARCHAR(100)                            NOT NULL,
    city    VARCHAR(60)                            NOT NULL,
    price   DECIMAL(12, 2)  NOT NULL DEFAULT 0,
    CONSTRAINT pk_restaurants PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_name
    ON restaurants(name DESC);

CREATE TABLE restaurant_availability
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    restaurant_id BIGINT NOT NULL,
    day_of_week   VARCHAR(20)                            NOT NULL,
    start         time WITHOUT TIME ZONE                  NOT NULL,
    "end"         time WITHOUT TIME ZONE                  NOT NULL,
    CONSTRAINT pk_restaurant_availability PRIMARY KEY (id),
    CONSTRAINT uc_restaurant_day UNIQUE (restaurant_id, day_of_week),
    CONSTRAINT fk_avail_restaurant
        FOREIGN KEY (restaurant_id)
        REFERENCES restaurants (id)
        ON DELETE CASCADE,
    CONSTRAINT check_start_before CHECK ( start < "end" )
);

CREATE INDEX IF NOT EXISTS idx_availability_restaurants
    ON restaurant_availability(restaurant_id);

CREATE TABLE tables
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    restaurant_id BIGINT NOT NULL ,
    code          VARCHAR(10) NOT NULL ,
    min_capacity  INTEGER                                 NOT NULL,
    max_capacity  INTEGER                                 NOT NULL,
    CHECK ( min_capacity > 0 AND max_capacity > 0 AND min_capacity<=max_capacity),
    CONSTRAINT pk_table PRIMARY KEY (id),
    CONSTRAINT uc_restaurant_code UNIQUE (restaurant_id, code),
    CONSTRAINT fk_table_on_restaurant
        FOREIGN KEY (restaurant_id)
        REFERENCES restaurants(id)
        ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_tables_by_rest
    ON tables(restaurant_id);



CREATE TABLE reservations
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    restaurant_id BIGINT NOT NULL ,
    user_id       BIGINT NOT NULL ,
    start         TIMESTAMP WITHOUT TIME ZONE NOT NULL ,
    "end"         TIMESTAMP WITHOUT TIME ZONE NOT NULL ,
    status        VARCHAR(10) NOT NULL ,
    version       BIGINT,
    CHECK ( status IN ('BOOKED', 'CANCELLED', 'COMPLETED', 'EXPIRED')),
    CHECK ( start < "end" ),
    CONSTRAINT pk_reservation PRIMARY KEY (id),
    CONSTRAINT fk_reservation_on_restaurant
        FOREIGN KEY (restaurant_id)
        REFERENCES restaurants(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_reservation_on_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE
);



CREATE INDEX IF NOT EXISTS idx_res_by_rest_start
    ON reservations (restaurant_id, start);

CREATE INDEX IF NOT EXISTS idx_res_status
    ON reservations(status);


CREATE TABLE reservation_tables
(
    reservation_id BIGINT NOT NULL,
    table_id       BIGINT NOT NULL,
    CONSTRAINT pk_reservation_tables PRIMARY KEY (reservation_id, table_id),
    CONSTRAINT fk_res_tab_on_reservation
        FOREIGN KEY (reservation_id)
        REFERENCES reservations(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_res_tab_on_table_entity
        FOREIGN KEY (table_id)
        REFERENCES tables (id)
        ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_rt_table
    ON reservation_tables(table_id);


CREATE TABLE inventory_rule
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    restaurant_id  BIGINT NOT NULL UNIQUE,
    default_duration_min INT NOT NULL,
    prep_buffer_min INT NOT NULL,
    cleanup_buffer_min INT NOT NULL,
    slot_granularity_min INT NOT NULL,
    CHECK (
        prep_buffer_min > 0 AND
        default_duration_min > 0 AND
        cleanup_buffer_min >= 0 AND
        slot_granularity_min >= 0),
    CONSTRAINT fk_inventory_on_restaurant
        FOREIGN KEY (restaurant_id)
        REFERENCES restaurants (id)
        ON DELETE CASCADE
);


CREATE TABLE payments
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    reservation_id BIGINT NOT NULL,
    provider VARCHAR(40) NOT NULL ,
    amount DECIMAL(12, 2)  NOT NULL DEFAULT 0,
    currency VARCHAR(3) NOT NULL ,
    status VARCHAR(10) NOT NULL ,
    external_id VARCHAR(64) NOT NULL ,
    CHECK ( status IN ('PENDING','SUCCEEDED','FAILED','CANCELED')),
    CONSTRAINT fk_payments_on_reservation
        FOREIGN KEY (reservation_id)
        REFERENCES reservations (id)
        ON DELETE CASCADE,
    CONSTRAINT uc_payment_ext UNIQUE (provider, external_id)
);

CREATE INDEX IF NOT EXISTS idx_pay_res
    ON payments(reservation_id);
